### PR TITLE
Create a reusable emptyContentState on first render

### LINKED ISSUE #91: Compatibility with Next.JS
CleanShot 2022-02-06 at 14 33 17@2x

Draft.JS runs into errors when working with Next.JS. This is a known issue and can be fixed by [creating a reusable emptyContentState like in this example.](https://github.com/facebook/draft-js/blob/master/examples/draft-0-10-0/universal/editor.js#L43-L53)

**Further reading**
- https://github.com/facebook/draft-js/issues/2427
- https://github.com/facebook/draft-js/issues/1199#issuecomment-331677160

### PR DESCRIPTION
**Pull request by mrzmyr**
Fixes #91

### CODE REVIEW

**Comment by mrzmyr** [comment]
Accidentally added b515c2ff25d24df73ad91f3b38127bfa800f8571, removed it in 5e40422ddb34dafad86346cecf7e82b98a09821b. Can create fresh PR if necessary.

**Comment by bonafideduck** [comment]
This seems fine to me.  I have to admit I don't fully understand the fix, but if:
1. My testing shows the application still works.
2. You have verified this fixes your issue.
3. You remove this line: `// const contentState = ContentState.createFromText(value);` :)

I'll push out an update - hopefully in the next few weeks.

**Comment by mrzmyr** [comment]
Removed this line: `// const contentState = ContentState.createFromText(value);`

**Comment by bonafideduck** [comment]
@mrzmyr 
Sorry to be a stickler, but have you verified this fixes the issue?

**Comment by bonafideduck** [comment]
@mrzmyr
My testing showed no issues with your code.  All that is left is verifying that you verified that this fixed your issue.

**Comment by mrzmyr** [comment]
Hi @bonafideduck, yes I can confirm it works for the case with next.js.

**Pull request merged**
